name = "DataSplits"
uuid = "c4daa60e-60e8-4e0a-bcf3-f80a6d479af9"
authors = ["Davide Crucitti <davide.crucitti@grheco.com>"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
